apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-4550"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-4550"
  template:
    metadata:
      labels:
        app: "myaks-4550"
    spec:
      containers:
        - name: "myaks-4550"
          image: "myakskuberegistry.azurecr.io/myaks"
          ports:
          - containerPort: 8080