on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myakskuberegistry.azurecr.io
        username: ${{ secrets.acr_myakskuberegistry_username }}
        password: ${{ secrets.acr_myakskuberegistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myakskuberegistry.azurecr.io/myaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push myakskuberegistry.azurecr.io/myaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaks-spring-boot-container-quickstart-ns | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaks-spring-boot-container-quickstart-ns`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaks-spring-boot-container-quickstart-ns
        container-registry-url: myakskuberegistry.azurecr.io
        container-registry-username: ${{ secrets.acr_myakskuberegistry_username }}
        container-registry-password: ${{ secrets.acr_myakskuberegistry_password }}
        secret-name: myaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaks-spring-boot-container-quickstart-ns
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          myakskuberegistry.azurecr.io/myaks:${{ github.sha }}
        imagepullsecrets: |
          myaksdockerauth
